# =========================== Basic Settings ===========================

model: models.graphs.neuralgraph:StaticNeuralGraph

# data
data: data.cifar10:CIFAR10
batch_size: 512
test_batch_size: 512
workers: 8

# lr for CE Loss
lr: 0.1
lr_scheduler: multistep
multistep_lr_milestones: [80, 120] # 80,120
multistep_lr_gamma: 0.1

# optimizer for CE Loss
optimizer: sgd
momentum: 0.9
weight_decay: 0.0001
nestorov: False

is_bilevel: True
second_optimizer : sgd
second_momentum: 0.9
second_weight_decay: 0.0001
nestrov: False

# info
output_size: 10
image_size: 32
num_epochs: 160
in_channels: 3
topk: [1,5]

# other
resume: ''
seed: 1996
save_dir: './checkpoints'
log_dir: './runs'
evaluate: False


# =========================== Override ===========================
val_resize: 32
prune_rate: 0.95
prune: True

dim: 800
downsample_dim: 32
feature_dim: 100
layers: 5

graph: dnw
setting: static
skip_profiling: True
alpha : 80 # edge probability controling param
threshold : 0.01
max_params : 1.6e+05
beta : 0.01 # flops_loss scale param - 1/b*log(1+e(b*(dflops))
